# Generated by Django 5.0.6 on 2024-05-23 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
